---
functional:
  - Пользователь должен иметь возможность регистрироваться и входить
  - Пользователь должен иметь возможность видеть во время решения задачи редактор с кодом другого игрока, а также вывод текстов
  - Пользователь должен иметь возможность менять язык программирования во время решения задачи
  - Пользователь должен иметь возможность играть с другим человеком, ботом или другом(переходя по ссылке)
  - Пользователь должен иметь возможность выбирать уровень сложности игры
  - Пользователь должен иметь возможность выбирать определённую игру, иначе она будет подобрана наугад
  - Пользователь должен иметь возможность изменять язык задачи с русского на английский и наоборот
  - Пользователь должен иметь возможность следить за ходом игры, либо просматривать запись игры
  - Пользователь должен иметь возможность писать и отправлять сообщения в чат, а также видеть сообщения других пользователей и и время отправки сообщения
  - Пользователь должен иметь возможность получать очки, на основе которых строится рейтинг за неделю, месяц и за всё время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Понятность и привлекательность интерфейса
  - Все элементы сайта должны быть читабельными(текст отображается, текст не закрыт кнопками, картинками, визуально легко читать информацию)
  - Присутствие обратной связи 
  - Наличие пагинации для рейтинга
  - Возможность перейти на главную страницу (лобби) из любого места на сайте
